version: 2.1

jobs:
  ensure_formatting:
    docker:
      - image: circleci/python:3.7.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: sudo pip3 install black
      - run:
          name: confirm black version
          command: black --version
      - run:
          name: run black check
          command: black --check .
  linter:
    docker:
      - image: alpine/flake8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: flake8
          command: flake8 --ignore=E,W ~/repo
  build:
    working_directory: ~/opencti-client
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip3 install -r requirements.txt --user
      - run:
          name: build
          command: python3 setup.py sdist bdist_wheel
      - persist_to_workspace:
          root: ~/opencti-client
          paths:
            - dist
  deploy:
    working_directory: ~/opencti-client
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - attach_workspace:
          at: ~/opencti-client
      - run:
          name: install dependencies
          command: pip3 install -r requirements.txt --user
      - run:
          name: verify git tag vs. version
          command: python3 setup.py verify
      - run:
          name: install twine
          command: sudo pip3 install twine
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = opencti" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: upload to pypi
          command: twine upload dist/*

workflows:
  version: 2
  check-code:
    jobs:
      - ensure_formatting
      - linter
  opencti_client_python:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              ignore: /.*/
